apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage

resources:
  - namespace.yaml
  - secrets.yaml
  - rbac.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - backstage.yaml
  - catalog.yaml
  - ingress.yaml

images:
  - name: backstage
    newName: docker.io/jaimehenao8126/backstage
    newTag: latest

patches:
  - path: patches/production.yaml

labels:
  - pairs:
      app: backstage
      managed-by: argocd